[workspace]
members = [
    "rustbof",
    "libs/bofalloc",
    "libs/bofentry",
    "libs/bofhelper"
]

[profile.dev]
panic = "abort"
opt-level = "z"
codegen-units = 1
strip = true

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
strip = true